/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#003d9b",
        "outline": "#737685",
        "inverse-primary": "#b2c5ff",
        "on-tertiary": "#ffffff",
        "primary-container": "#0052cc",
        "on-tertiary-fixed-variant": "#723600",
        "tertiary-container": "#904600",
        "outline-variant": "#c3c6d6",
        "inverse-on-surface": "#f0f0fb",
        "primary-fixed-dim": "#b2c5ff",
        "on-secondary-fixed-variant": "#930010",
        "background": "#faf8ff",
        "primary-fixed": "#dae2ff",
        "on-error-container": "#93000a",
        "tertiary": "#6c3300",
        "on-surface": "#191b23",
        "surface-variant": "#e1e2ec",
        "on-secondary-container": "#fffbff",
        "surface-container": "#ededf8",
        "on-error": "#ffffff",
        "surface-tint": "#0c56d0",
        "on-primary-fixed-variant": "#0040a2",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2e3038",
        "surface": "#faf8ff",
        "secondary-container": "#da3433",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e1e2ec",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#410003",
        "on-tertiary-container": "#ffc7a3",
        "tertiary-fixed": "#ffdcc6",
        "surface-dim": "#d9d9e4",
        "surface-container-low": "#f3f3fd",
        "secondary-fixed-dim": "#ffb3ac",
        "on-primary-container": "#c4d2ff",
        "secondary": "#b6171e",
        "surface-container-high": "#e7e7f2",
        "surface-bright": "#faf8ff",
        "on-tertiary-fixed": "#311300",
        "on-background": "#191b23",
        "tertiary-fixed-dim": "#ffb786",
        "on-primary-fixed": "#001848",
        "secondary-fixed": "#ffdad6",
        "on-surface-variant": "#434654",
        "triage-critical": "#ba1a1a",
        "triage-high": "#f97316",
        "triage-medium": "#fbbf24",
        "triage-low": "#22c55e",
        "triage-general": "#0052cc"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-md": "12px",
        "container-margin": "24px",
        "stack-sm": "4px",
        "stack-lg": "24px",
        "gutter": "16px",
        "unit": "8px",
        "sidebar-width": "260px",
        "incident-panel-width": "380px"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "display-critical": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-bold": ["14px", {"lineHeight": "20px", "fontWeight": "700"}],
        "display-critical": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
